pointcloud_to_laserscan_node:
  ros__parameters:
    target_frame: base_link      # 目标坐标系
    transform_tolerance: 0.01    # 坐标变换的容忍时间
    min_height: -1.0              # 点云的最小高度
    max_height: 1.0              # 点云的最大高度
    angle_min: -3.1415927        # 激光扫描的最小角度（弧度）
    angle_max: 3.1415927         # 激光扫描的最大角度（弧度）
    angle_increment: 0.0174532923  # 激光扫描的角度增量
    scan_time: 0.5333            # 扫描时间
    range_min: 0.12              # 激光扫描的最小范围
    range_max: 18.0              # 激光扫描的最大范围
    use_inf: true                # 是否使用无穷大值表示最大范围
    inf_epsilon: 1.0             # 无穷大值的近似值
    concurrency_level: 1          # 并发级别
    'point_cloud_topic': '/cloud_in' # 输入的点云话题
    'scan_topic': '/scan'      
    scan_qos:
      reliability: "reliable"  
      history: "keep_last"     
      depth: 10                 